# Generated by Django 5.0.3 on 2024-04-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialplatform', '0003_alter_post_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
